server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      users-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        ignoreExceptions:
          - com.mini_ecommerce.orders_service.exception.NotFoundException
      products-service:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        ignoreExceptions:
          - com.mini_ecommerce.orders_service.exception.NotFoundException
  retry:
    instances:
      users-service:
        maxAttempts: 3
        waitDuration: 500ms
        ignoreExceptions:
          - com.mini_ecommerce.orders_service.exception.NotFoundException
      products-service:
        maxAttempts: 3
        waitDuration: 500ms
        ignoreExceptions:
          - com.mini_ecommerce.orders_service.exception.NotFoundException

logging:
  level:
    com.mini_ecommerce.orders_service.client: DEBUG
    com.mini_ecommerce.orders_service.service.UserLookupService: INFO
    com.mini_ecommerce.orders_service.service.ProductLookupService: INFO
    io.github.resilience4j.circuitbreaker: INFO
    io.github.resilience4j.retry: INFO

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
